### ISSUE TITLE
Multiple sessions

### ISSUE THREAD

**Issue by markitosgv** [gesdinet/JWTRefreshTokenBundle#1]
I think is a good enhancement to make this bundle can handle many refresh tokens for different sessions. Do you have any idea how can implement this?

**Comment by wujku** [comment]
+1

**Comment by markitosgv** [comment]
@wujku im thinking about it, i think is better extract refreshToken from UserEntity and make a new entity called Token with User_ID, RefreshToken.

In this way we could have more than one refresh token per user.

The flow then works like this:

A user logs in (with his credentials) then we generate a new refresh_token in system.
A user use his refresh_token to log in, then we revoke the current refresh_token and generate another one.

One problem im seeing is how to revoke unused refresh_tokens, i mean, if i log in in one app using credentials many times, i generate many refresh_tokens that persist forever.

Do you think is a good practice include an expiration date in Token entity?

In this way we could invalidate refresh_tokens when date expires.

**Comment by wujku** [comment]
You could add date of expiration to Token entity. 
Token expiration time may be 2-3 times longer than json token.
I would add the parameter to set the expiration time of the Token manually.

**Comment by markitosgv** [comment]
Yes we can configure token_refresh ttl as a config parameter. 

And maybe create a command to use as cron to remove invalid refresh tokens

**Comment by wujku** [comment]
Or create a simple query to clean the old entries during refresh action.

**Comment by wujku** [comment]
@markitosgv at first sight everything looks good. 
Does Username is necessary when refreshing the token? In my opinion, it would suffice use UserRefreshTokenManager and get associated user by refresh token from request.

**Comment by markitosgv** [comment]
im going to open another issue about this question and unique token problem
