### ISSUE TITLE
JWTRefreshTokenBundle usage of refresh token as a service Issue

### ISSUE THREAD

**Issue by rlRahul1989** [gesdinet/JWTRefreshTokenBundle#103]
I currently installed JWTRefreshTokenBundle and it throws and error as:
Compile Error: Cannot use Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken as RefreshToken because the name is already in use.

I think the issue occurred in the latest pull. I already used the bundle, but at that time it worked fine. I am using Symfony3.4

**Comment by ingvald31** [comment]
Hey, did you find a solution ? I have the same problem ...

**Comment by georgwaechter** [comment]
same problem here after upgrading from symfony 2.8 to symfony 3.4
