### ISSUE TITLE
Why database access at all, use JWT

### ISSUE THREAD

**Issue by Vaxter** [gesdinet/JWTRefreshTokenBundle#105]
Instead of generating random token and storing it to database, think about using another JWT as a refresh token.
Refresh token generated this way will have the expiry information in it, so no database access is needed for validation, except for blacklisting which could be optional.

**Comment by trsteel88** [comment]
I had the same thought @Vaxter. However, by having it in your database you can delete tokens and force the user to authenticate. This means that if a user changes their password, you could purge all their refresh tokens and they would need to re-auth on other devices.
