### ISSUE TITLE
Installation issue with Mongodb 

### ISSUE THREAD

**Issue by devbyekru** [gesdinet/JWTRefreshTokenBundle#111]
Hi,
I'm using mongodb, when i tried to install latest version ((>=v0.5.1), I am getting following error. 
``` [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineOrmMappingsPass" from namespace "Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler".
!!  Did you forget a "use" statement for another namespace? in /var/www/html/vendor/gesdinet/jwt-refresh-token-bundle/DependencyInjection/Compiler/DoctrineMappingsCompilerPass.php:55
!!  Stack trace:
!!  #0 /var/www/html/vendor/gesdinet/jwt-refresh-token-bundle/DependencyInjection/Compiler/DoctrineMappingsCompilerPass.php(32): Gesdinet\JWTRefreshTokenBundle\DependencyInjection\Compiler\DoctrineMappingsCompilerPass->getORMCompilerPass(Array)
!!  #1 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Gesdinet\JWTRefreshTokenBundle\DependencyInjection\Compiler\DoctrineMappingsCompilerPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #2 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(736): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Sy in /var/www/html/vendor/gesdinet/jwt-refresh-token-bundle/DependencyInjection/Compiler/DoctrineMappingsCompilerPass.php on line 55
!!
Script @auto-scripts was called via post-update-cmd
```
I don't have orm installed, instead I am using mongodb odm.

**Comment by markitosgv** [comment]
Hi @devbyekru ,

Did you check this https://github.com/gesdinet/JWTRefreshTokenBundle#select-manager-type?

**Comment by juliangut** [comment]
I've just reviewed and I think I know what the problem might be

Out of the box the library expects you to use ORM but you're going to use ODM so you don't require ORM
Just in the moment of installation cache clear is triggered assuming you're using ORM and thus it ends in this line: https://github.com/gesdinet/JWTRefreshTokenBundle/blob/8843ae0bb8930c716ea269f05211a6b5a5279ac1/DependencyInjection/Compiler/DoctrineMappingsCompilerPass.php#L55 throwing the ClassNotFoundException

If you set the parameter @markitosgv referenced you should be good to do composer install

But this doesn't fix the installation problem, I'd suggest to verify ORM/ODM existence before processing mappings, here: https://github.com/gesdinet/JWTRefreshTokenBundle/blob/8843ae0bb8930c716ea269f05211a6b5a5279ac1/DependencyInjection/Compiler/DoctrineMappingsCompilerPass.php#L30

**Comment by juliangut** [comment]
I'll try to make a PR tonight to fix installation WITHOUT Doctrine's ORM

This should also be documented right in the installation section on readme file, although people using ORM won't suffer this problem

**Comment by devbyekru** [comment]
Hi @juliangut , We still have the issue of dependency while installing the library. 

The service "gesdinet.jwtrefreshtoken.refresh_token_manager" has a dependen
  cy on a non-existent service "doctrine.orm.entity_manager".

And can remove only by setting the parameter  `manager_type: mongodb` 

```
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
!!
!!    The service "gesdinet.jwtrefreshtoken.refresh_token_manager" has a dependen
!!    cy on a non-existent service "doctrine.orm.entity_manager".
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by juliangut** [comment]
The problem here is the library assumes you're going to use ORM and thus configures itself as such

The normal use case is installing this in a project already having ORM installed too. The problem comes when you want to use ODM from scratch and the library still expects ORM

There is only one solution I can foresee check for ORM and depending on it being present or not assume your configuration:

* If ORM present assume you're going to use ORM
* If you DON'T have ORM assume you're going to use ODM

The problem will come when you don't have ANY of those (not following installation instructions) in that case  the problem will be ```[...] non-existent service "doctrine_mongodb.odm.document_manager"'``` but in this scenario it really is your fault

I'm getting a PR ready
