### ISSUE TITLE
Retrieve refresh token from cookie

### ISSUE THREAD

**Issue by Cochonours** [gesdinet/JWTRefreshTokenBundle#132]
I'd like to retrieve the refresh token from a http only cookie in order to limit security risk by disollowing access from JS. Could you help me to achieve that?

I tried modifying the default route, but the "gesdinet.jwtrefreshtoken:refresh" is full of private data so I can't just extend that class and change the behaviour I want.

**Comment by markitosgv** [comment]
Hi,

The key is here: 
https://github.com/gesdinet/JWTRefreshTokenBundle/blob/604b70c86e557c70105b8850eb44426ab2056a9d/Security/Authenticator/RefreshTokenAuthenticator.php#L57

We expect getting refresh token from body or as parameter (get or post)

    public static function getRefreshToken(Request $request)
    {
        $refreshTokenString = null;
        if (false !== strpos($request->getContentType(), 'json')) {
            $content = $request->getContent();
            $params = !empty($content) ? json_decode($content, true) : array();
            $refreshTokenString = isset($params['refresh_token']) ? trim($params['refresh_token']) : null;
        } elseif (null !== $request->get('refresh_token')) {
            $refreshTokenString = $request->get('refresh_token');
        }
        return $refreshTokenString;
    }

You could hack into this creating an event listener and modifying your request. You could do something like:

```php
        $request->attributes->set('refresh_token', $request->cookies->get('refresh_token'));
```

**Comment by konshensx16** [comment]
Hey there guys, 

I have a question about refreshing the token, is it okay okay to refresh the token on each request, or only when the token expires?

**Comment by faysalnasim** [comment]
+1

**Comment by raiabdullahbashir** [comment]
here i am saving cookies

res.cookie("refresh_token", refresh_token, {
        httpOnly: true,
        path: "/user/refresh_token",
        maxAge: 1 * 24 * 60 * 60 * 1000, // 7 days
      });

here i am getting cookies

const rf_token = req.cookies.refresh_token;


am i doing it wrong way?
