### ISSUE TITLE
Unrecognized options "path, defaults" under "gesdinet_jwt_refresh_token" in SF4

### ISSUE THREAD

**Issue by patrickmaynard** [gesdinet/JWTRefreshTokenBundle#135]
After completing step 3 (routing configuration), I try to clear my Symfony cache using `bin/console cache:clear` and get the following error:

> In ArrayNode.php line 311:
> 
>   Unrecognized options "path, defaults" under "gesdinet_jwt_refresh_token"

**Comment by markitosgv** [comment]
Hi @patrickmaynard it seems you've an invalid configuration for this bundle.

Check this: https://github.com/gesdinet/JWTRefreshTokenBundle/blob/master/DependencyInjection/Configuration.php

We don't have "path, defaults" configuration tags, maybe you've got wrong syntax in your config.yml file?

**Comment by patrickmaynard** [comment]
Ah -- I accidentally used the Symfony 3 version. Thanks for catching that.
