### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by patrickmaynard** [gesdinet/JWTRefreshTokenBundle#136]
We have a working app that successfully returns a token from `/auth/user-token`. After I install JWTRefreshTokenBundle, (completing the installation up through step 3), however, I get this error when visiting that existing endpoint:

> An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

Reverting my files to a pre-installation state allows the app to work again. 

Does anyone have any ideas about what might be going on here? 

===

Update: Attempting to run the installation through step 5 (schema update) results in this error:

> In AbstractMySQLDriver.php line 113:
> 
>   An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
> 
> 
> In PDOConnection.php line 50:
> 
>   SQLSTATE[HY000] [2002] Connection refused
> 
> 
> In PDOConnection.php line 46:
> 
>   SQLSTATE[HY000] [2002] Connection refused

**Comment by norkunas** [comment]
@patrickmaynard did you resolve your issue?

**Comment by patrickmaynard** [comment]
@norkunas nope -- still seeing the same issue.

**Comment by norkunas** [comment]
Did you test connection manually, is it working properly?

**Comment by patrickmaynard** [comment]
That's funny ... pulling fresh changes from our develop branch seems to have fixed the issue. I have no idea what changed.
