### ISSUE TITLE
Fatal error when refresh token is experied

### ISSUE THREAD

**Issue by pdoreau** [gesdinet/JWTRefreshTokenBundle#15]
Hi. When I try to renew a token which is expired :

    Catchable Fatal Error: Object of class Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken could not be converted to string

=> vendor/gesdinet/jwt-refresh-token-bundle/Service/RefreshToken.php at line 70

I guess toString method should be implemented.

**Comment by markitosgv** [comment]
You're right. When RefreshToken is invalid or doesn't exists, it throw a AuthenticationException, and we need to implement toString() method in RefreshToken entity.

```php
if (null === $refreshToken || !$refreshToken->isValid()) {
            return $this->failureHandler->onAuthenticationFailure($request,
                new AuthenticationException(
                    sprintf('Refresh token "%s" is invalid.', $refreshToken)
                )
            );
}
```

We solved in last commit #
