### ISSUE TITLE
does not work in Symfony 4.3 but does in 4.2 - doctrine .yml problem?

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [gesdinet/JWTRefreshTokenBundle#151]
When upgrading from Symfony 4.2 to 4.3, the mappings did not work correctly anymore and I got errors like 'Property "refreshToken" does not exist in class "Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken"'

Downgrading the refresh token bundle to v0.3.3 seems to work fine

It seems doctrine .yml mappings will be deprecated, see:
https://github.com/doctrine/DoctrineBundle/issues/776
maybe that's the cause?
 (the downgraded bundle still uses annotations)

**Comment by markitosgv** [comment]
@24HOURSMEDIA did you men doesn't work in Symfony 4.4 but works ok in 4.3? Is symfony 4.4 enforcing to upgrade to any doctrine package version?

**Comment by 24HOURSMEDIA** [comment]
Sorry, I meant Symfony 4.2
If I write a custom entity for the refresh token (using annotations) the latest version works

**Comment by oschwartz** [comment]
Hi same problem in 4.3 Property "refreshToken" does not exist in class "Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken"

**Comment by norkunas** [comment]
This is not related to this library itself but with symfony auto validator https://github.com/symfony/symfony/issues/31715

**Comment by markitosgv** [comment]
thanks @norkunas we'll wait for this issue be resolved to mark this issue as closed

**Comment by xabbuh** [comment]
Can you confirm that symfony/symfony#31836 fixes the issue?

**Comment by lsv** [comment]
This fix https://github.com/symfony/symfony/pull/31836#issuecomment-499039646 does fix the issue.
I havent tried symfony/master yet.

**Comment by markitosgv** [comment]
Solved in Symfony 4.3.1 release, please update your project.
