### ISSUE TITLE
Property "refreshToken" does not exist in class

### ISSUE THREAD

**Issue by pesseyjulien** [gesdinet/JWTRefreshTokenBundle#153]
Hi,

After a recent update of your bundle, I now get the following error on 'login_check' :

`Property "refreshToken" does not exist in class "Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken"`

Any idea how to fix this ?

Thanks in advance for your help,
Julien

**Comment by barabah** [comment]
Same issue

**Comment by markitosgv** [comment]
Solved in Symfony 4.3.1 release, pleas update
