### ISSUE TITLE
 Unrecognized option "single_use"

### ISSUE THREAD

**Issue by chasovskih-grisha** [gesdinet/JWTRefreshTokenBundle#158]
`
Unrecognized option "single_use" under "gesdinet_jwt_refresh_token". Available options are "entity_manager", "firewall", "manager_type", "object_manager", "refresh_token_class", "refresh_token_entity", "token_parameter_name", "ttl", "ttl_update", "user_checker", "user_identity_field", "user_provider".
`

**Comment by markitosgv** [comment]
Which version are you using?

**Comment by chasovskih-grisha** [comment]
Thanks! I'm using 0.6.2
