### ISSUE TITLE
Refresh Token Unique and Secure

### ISSUE THREAD

**Issue by markitosgv** [gesdinet/JWTRefreshTokenBundle#2]
Hi,

Function that generate refresh token is this

```php
bin2hex(openssl_random_pseudo_bytes(64));
```

I think is a good way to create a secure random string. But maybe its not unique. Because of this I ask for username when you need to refresh token. 

Do you think is possible if we have so many database users that two valid refresh tokens be repeated?

**Comment by wujku** [comment]
Function looks good, but you should read this:
http://timoh6.github.io/2013/11/05/Secure-random-numbers-for-PHP-developers.html

Make token field as unique, then catch NonUniqueException and regenerate token If it is necessary.

**Comment by markitosgv** [comment]
It sounds good to make refresh token unique and catch exceptions to regenerate. With this change we can avoid to ask for username
