### ISSUE TITLE
no new refresh token on credentials authentication

### ISSUE THREAD

**Issue by benvanmierloo** [gesdinet/JWTRefreshTokenBundle#20]
Scenario:

1) Auth with credentials for user 1:
token: abc
refresh_token: xyz

2) Get new token with refresh_token:
token: def
refresh_token: xyz

3) token expired, auth with credentials for user 1:
token: ghi
refresh_token: xyz

4) optionally login from another browser with user 1 credentials:
token: jkl
refresh_token: xyz

I don't think that in step 3) and/or 4) the same token should be returned. Every credentials authentication should generate a new refresh_token.

**Comment by markitosgv** [comment]
You're right. I think its better to generate a new refresh token in every scenario.

For example in case 4 if we generate new tokens then you can revoke token only for some clients.

To avoid broke some clients compatibility we need to work on this and tag as a new release.

**Comment by benvanmierloo** [comment]
well, not generate a new refresh_token in every scenario, only when credentials are supplied (step 1, 3 or 4). When refreshing a (access) token using a refresh_token (step 2), the same refresh_token can be used.

**Comment by markitosgv** [comment]
Well its a possibility, if you want as a client to revoke the token you can logout.

**Comment by benvanmierloo** [comment]
Please review the pull request I've done concerning this issue. I have one more question. Why did the refresh_tokens extend their validity every time a refresh is done? It seems to me this poses a security risk. Refresh tokens can possibly be valid until the end of time

**Comment by benvanmierloo** [comment]
Hi, please check my comments in the pull request. Thanks
