### ISSUE TITLE
Not working with LexikJWTAuthenticationBundle 1.7.0

### ISSUE THREAD

**Issue by Seb33300** [gesdinet/JWTRefreshTokenBundle#46]
Since LexikJWTAuthenticationBundle 1.7.0
See https://github.com/lexik/LexikJWTAuthenticationBundle/pull/200

This bundle is not working anymore.

> An Exception was thrown while handling: Catchable Fatal Error: Argument 1 passed to Gesdinet\JWTRefreshTokenBundle\Request\RequestRefreshToken::getRefreshToken() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in gesdinet\jwt-refresh-token-bundle\EventListener\AttachRefreshTokenOnSuccessListener.php on line 44 and defined

**Comment by markitosgv** [comment]
@Seb33300 I think you are using an old version. In this PR is solved https://github.com/gesdinet/JWTRefreshTokenBundle/pull/45.

**Comment by Seb33300** [comment]
I don't know why composer update do not update your bundle.

I needed to manually remove the gesdinet/JWTRefreshTokenBundle directory in the vendor directory and make another composer update to get the last version.
