### ISSUE TITLE
Generate refresh token inside a controller

### ISSUE THREAD

**Issue by ChainsOfPower** [gesdinet/JWTRefreshTokenBundle#49]
Hi,
i need to generate a new refresh token when user changes it's username because in that case old refresh token becomes invalid. I can generate JWT token with $token = $this->get('lexik_jwt_authentication.jwt_manager')->create($user);, but can't manage to do the same with refresh token. Am i missing something, or there is no way to do it?

**Comment by Youassi** [comment]
Hey 
I managed to do it but I don't know if this is a best practice here is my code>>>

use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationSuccessEvent;
use Symfony\Component\HttpFoundation\Response;
          $response = new Response();
                    $event = new AuthenticationSuccessEvent(array(), $user, $response);
                    $token = $this->get('lexik_jwt_authentication.jwt_manager')->create($user);
                    $this->get('gesdinet.jwtrefreshtoken.send_token')->attachRefreshToken($event);//generer le refresh_token
                    $refresh_token = $this->get('gesdinet.jwtrefreshtoken.refresh_token_manager')->getLastFromUsername($user->getUsername());

**Comment by blaues0cke** [comment]
The solution from @youassi is working, here a well formatted version:

```
use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken;
use Gesdinet\JWTRefreshTokenBundle\EventListener\AttachRefreshTokenOnSuccessListener;

/**
 * @var $attachRefreshTokenOnSuccessListener AttachRefreshTokenOnSuccessListener
 */
protected $attachRefreshTokenOnSuccessListener;

/**
 * @var $refreshTokenManager RefreshTokenManager
 */
protected $refreshTokenManager;

/**
 * UserApiSubscriber constructor.
 *
 * @param JWTManager $jwtManager
 * @param EntityManager $entityManager
 * @param AttachRefreshTokenOnSuccessListener $attachRefreshTokenOnSuccessListener
 * @param RefreshTokenManager $refreshTokenManager
 */
public function __construct(
    ...
    AttachRefreshTokenOnSuccessListener $attachRefreshTokenOnSuccessListener,
    RefreshTokenManager $refreshTokenManager
)
{
    $this->attachRefreshTokenOnSuccessListener = $attachRefreshTokenOnSuccessListener;
    $this->refreshTokenManager                 = $refreshTokenManager;
}

/**
 * @param User $user
 * @return string
 */
protected function getRefreshTokenForUser(User $user)
{
    $response        = new Response();
    $jwtSuccessEvent = new AuthenticationSuccessEvent(array(), $user, $response);

    $this->attachRefreshTokenOnSuccessListener->attachRefreshToken($jwtSuccessEvent);

    $refreshToken    = $this->refreshTokenManager->getLastFromUsername($user->getUsername());

    return $refreshToken->getRefreshToken();
}
```

```
user.api_subscriber:
    arguments:
        ...
        - '@gesdinet.jwtrefreshtoken.send_token'
        - '@gesdinet.jwtrefreshtoken.refresh_token_manager'
    class: AppBundle\Subscriber\UserApiSubscriber
    tags:
        - { name: kernel.event_subscriber }
```
