### ISSUE TITLE
What's happened if users swap their usernames ?

### ISSUE THREAD

**Issue by kevin-lot** [gesdinet/JWTRefreshTokenBundle#72]
This bundle "links" user table and refresh token table with username field.
What's happened if users swap their usernames ?

Maybe I miss some codes but I see a real security issue.
Why do you not use relationship with foreign key between user table and refresh token table ?

Best regards.

**Comment by markitosgv** [comment]
Hi!

Well I think if your user changes his name you must remove all user related refresh tokens to avoid security issues, and create a new one that belongs to the new username.

**Comment by trsteel88** [comment]
I use user_identity_field as the id for this reason. The account they authenticate with will always be the returned user regardless of email/username.
