### ISSUE TITLE
Refresh token never returned after custom token generation.

### ISSUE THREAD

**Issue by sensorario** [gesdinet/JWTRefreshTokenBundle#75]
I generate jwt token using "lexik_jwt_authentication.encoder" service. In JWTRefreshTokenBundle's readme file I see that LexikJWTAuthenticationBundle now should returns a JWT Token and a Refresh Token data.

```
        $token = $this->get('lexik_jwt_authentication.encoder')
            ->encode([
                'username' => $user->getUsername(),
                'exp'      => (new \DateTime('+40 seconds'))->getTimestamp(),
            ]);
```

$token variable does not contains refresh token. In database, refresh_tokens table does not contains any token.

**Comment by aurimas535** [comment]
You should user JWT authentication success handler. This handler add
 refresh token into database. 

```
$jwt = $this->container->get('lexik_jwt_authentication.jwt_manager')->create($user);
$authenticationSuccessHandler->handleAuthenticationSuccess($user, $jwt);
```

If you want to claim it directly you can do that like that:

```
$response = $authenticationSuccessHandler->handleAuthenticationSuccess($user, $jwt);
$decodedResponse = json_decode($response->getContent(), true);
$refreshToken = $decodedResponse['refresh_token'];
```

**Comment by llaville** [comment]
Hello,
I've recently used the package and does found the solution until I see this issue report.
I suggest that it should be include in the README file.

Thanks.
Laurent
