### ISSUE TITLE
I can't extend Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken class if I want MongdDB document

### ISSUE THREAD

**Issue by xorik** [gesdinet/JWTRefreshTokenBundle#76]
Hi.

I'm trying to store refresh tokens in a mongodb, so I'm extend `Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken` but in this case nothing is working because of `@UniqueEntity` annotation on the base class. So I need to copy all methods to my class.

It would be great, if I can avoid this copy-paste.

Thanks

**Comment by markitosgv** [comment]
Sorry but this bundle doesn't support Doctrine ODM bundle

**Comment by xorik** [comment]
@markitosgv no, it's working perfectly
I set refresh_token_entity to my mongodb document and set
`entity_manager: doctrine.odm.mongodb.document_manager`

Only problem is I need to copy+paste all methods from the base class

**Comment by markitosgv** [comment]
Nice to hear that, then we have to think about how to improve this to support both.

**Comment by redayoub** [comment]
+1

**Comment by t4tomy** [comment]
@xorik I have also done the same, but unfortunately can't able to to work it properly. Could you please share how exactly you have done that. Thanks
