### ISSUE TITLE
Add endpoint for clients who wants to revoke tokens

### ISSUE THREAD

**Issue by markitosgv** [gesdinet/JWTRefreshTokenBundle#8]
API clients can logout deleting its refresh_token. But this only works in client side, i mean, if someone has got refresh_token could do a login again.

The idea is to set an endpoint like /api/token/revoke which accepts a POST with refresh_token to revoke access.
#### Extra

Add another endpoint to revoke all tokens related to a user.

To call both endpoints user needs to be logged, of course. In other words, this endpoint has to be under JWT firewall.

**Comment by murilozilli** [comment]
I have some functionality where I add new roles to the user and it would be great if when that happens I could revoke his current tokens so he needs to login again
