### ISSUE TITLE
How to set user_provider to Doctrine user provider?

### ISSUE THREAD

**Issue by loffler** [gesdinet/JWTRefreshTokenBundle#94]
Hello,
as per api-platform's [recommedations](https://api-platform.com/docs/core/fosuser-bundle/), I am using [Doctrine user provider](https://symfony.com/doc/current/security/entity_provider.html) in my API. 

So, my User entity looks like this:
```
// src/Api/Entity/User.php
namespace App\Api\Entity;
class User implements UserInterface, \Serializable {...}
```

Now I have no idea how to configure user_provider. I tried to set it like this:
```
# config/packages/gesindet_jwt_refresh_token.yaml
gesdinet_jwt_refresh_token:
    user_provider: app.api.entity.user
```
 But I'm getting this error:
`Type error: Argument 1 passed to ...\RefreshTokenProvider::setCustomUserProvider() must implement interface ...\UserProviderInterface, null given`

Do you have any idea how do I set user_provider path properly, please?

**Comment by sandoche** [comment]
Just found the solution I put this
```
gesdinet_jwt_refresh_token:
    user_provider: security.user.provider.concrete.user_provider
```

And my security.yaml is the following
```
security:
#...
    providers:
        user_provider:
            entity:
                class: App\Entity\User
#...
```

**Comment by mangelsnc** [comment]
Hi @sandoche!

In what version of Symfony are you working? With Symfony 4 that service does not exists :(

**Comment by mangelsnc** [comment]
Forget it @sandoche, you are right and I'm a monkey patcher... 😅 

My provider is not called `user_provider`, so its very improbable that Symfony will found that service.

Already fixed, thanks!

**Comment by loffler** [comment]
@sandoche sorry I forgot to reply earlier. I can also confirm that your solution just works fine, thank you!

**Comment by meetmatt** [comment]
@loffler I think this info has to be noted in the documentation. I broke my head in the internals to find out under which name the Security component registers custom user providers. Do you want a PR for documentation?
